[workspace]
authors = ["Chandler May <chandler.camille.may@gmail.com>"]
channels = ["conda-forge"]
name = "text-detection-baselines"
platforms = ["win-64", "linux-64", "osx-arm64", "linux-aarch64"]
version = "0.1.0"
preview = ["pixi-build"]

[environments]
default = {features = [], solve-group = "base-python"}
test = {features = ["test"], solve-group = "base-python"}
dev = {features = ["test", "dev"], solve-group = "base-python"}
base-python = ["py312"]
test313 = ["test", "py313"]
test314 = ["test", "py314"]

[pypi-dependencies]
text-detection-baselines = {path = "."}

[dependencies]
python = ">=3.12,<3.15"
click = ">=8.3.1,<9"

[feature.py312.dependencies]
python = "~=3.12.0"

[feature.py313.dependencies]
python = "~=3.13.0"

[feature.py314.dependencies]
python = "~=3.14.0"

[feature.test.dependencies]
ruff = ">=0.15.0,<0.16"

[feature.dev.dependencies]
ipython = ">=9.10.0,<10"

[feature.test.tasks]
_ruff = "ruff check"
_pytest = "pytest"
test = [{ task = "_ruff" }, { task = "_pytest" }]

[package]

[package.build.backend]
name = "pixi-build-python"
version = "==0.4.0"

[package.host-dependencies]
hatchling = "*"
